Repository fnplus/footsteps-extension, pull requests merged in 2020-04, with the labels that each got.

#30 added auto-assign.yml
  .github/auto-assign.yml
Labels: beginner, gssoc

#31 Create autosquash-commits.yml
  .github/autosquash-commits.yml
Labels: beginner, gssoc20

#34 Create gitCret.yml
  .github/gitCret.yml
Labels: beginner, gssoc20

#33 Create check-broken-link.yml
  .github/check-broen-link.yml
Labels: beginner, gssoc20

#41 Code quality increase.
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  README.md
  scripts/build.js
  src/auth/auth.js
  src/background.js
  src/content.js
  src/lib/content/helpers.js
  src/lib/content/parser.js
  src/lib/test.js
  src/popup/popup.js
Labels: easy, gssoc20
